[tool.poetry]
name = "APIcord"
version = "0.0.1.2"
description = ""
authors = ["Lucas <lmail@e.email>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
flask = "^1.1.2"
replit = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
